# Generated by Django 4.1.4 on 2023-01-05 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_aamall_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aamall',
            name='user',
        ),
        migrations.RemoveField(
            model_name='image',
            name='adl',
        ),
        migrations.RemoveField(
            model_name='image',
            name='photo',
        ),
        migrations.AddField(
            model_name='aamall',
            name='author',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aamall',
            name='thumbnail_url',
            field=models.URLField(blank=True, max_length=234, null=True),
        ),
    ]
