# Generated by Django 4.1.4 on 2023-01-26 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_remove_aamall_user_remove_image_adl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aamall',
            name='photo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='listings.image'),
            preserve_default=False,
        ),
    ]
