# Generated by Django 4.1.4 on 2023-02-28 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_alter_aamall_description_alter_aamall_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aamall',
            name='photo',
        ),
        migrations.AddField(
            model_name='aamall',
            name='image',
            field=models.URLField(blank=True, max_length=234, null=True),
        ),
    ]
