# Generated by Django 4.1.4 on 2023-04-12 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_rename_category_aamall_cat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aamall',
            name='phone',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
